#!/bin/bash

echo "🚀 Digital Health Cartoon 배포 가이드"
echo "======================================"
echo ""
echo "📋 현재 상태:"
echo "- ✅ 코드 GitHub에 푸시 완료"
echo "- ✅ README 작성 완료"
echo "- ✅ GitHub Actions 설정 완료"
echo "- ⏳ Cloudflare 배포 진행 중"
echo ""
echo "🌐 배포 주소:"
echo "- 프론트엔드: https://mosi-second-job.pages.dev"
echo "- 백엔드 API: https://digital-health-cartoon-api.moses-song.workers.dev"
echo ""
echo "🔧 수동 배포 단계:"
echo ""
echo "1. Cloudflare Pages 설정:"
echo "   - https://dash.cloudflare.com/pages"
echo "   - GitHub 리포지토리 연결"
echo "   - 빌드 명령어: cd digital-health-cartoon/frontend && npm run build"
echo "   - 출력 디렉토리: digital-health-cartoon/frontend/dist"
echo ""
echo "2. Cloudflare Workers 설정:"
echo "   - https://dash.cloudflare.com/workers"
echo "   - wrangler.toml 파일로 배포"
echo "   - 환경변수 설정 필요:"
echo "     - GEMINI_API_KEY: AIzaSyBPFlxm8zvR7aHqS-1Tfuh5Ps24MRMs8Q8"
echo "     - YOUTUBE_API_KEY: AIzaSyDAMWthh8vcjvjuBS2lZHwzp_NCR5xrKUk"
echo ""
echo "3. 로컬 테스트:"
echo "   cd digital-health-cartoon/backend && npm run dev"
echo "   cd digital-health-cartoon/frontend && npm run dev"
echo ""
echo "🔍 문제 해결:"
echo "- '웹페이지를 찾을 수 없다' 에러 시:"
echo "  1. Cloudflare Pages 빌드 로그 확인"
echo "  2. GitHub Actions 실행 상태 확인"
echo "  3. Workers API 배포 상태 확인"
echo ""
echo "✅ 준비 완료된 파일들:"
echo "- digital-health-cartoon/frontend/dist/ (프론트엔드 빌드)"
echo "- cloudflare-worker/ (백엔드 Workers)"
echo "- .github/workflows/ (자동 배포)"
echo ""