#!/bin/bash

echo "🔑 Cloudflare API 토큰 권한 정확한 가이드"
echo "========================================"
echo ""

echo "🎯 당신이 필요한 권한:"
echo "✅ Workers Scripts:Edit"
echo "✅ Workers KV Storage:Edit" 
echo "✅ Cloudflare Pages:Edit"
echo ""

echo "🔍 계정 권한 문제일 가능성이 높음!"
echo "Workers 페이지가 안 보이는 건 권한 문제임"
echo ""

echo "⚡ 즉시 해결책 2가지:"
echo ""

echo "🌟 방법 1: 새 계정으로 API 토큰 생성"
echo "1. https://dash.cloudflare.com/sign-up"
echo "2. Custom token 생성"
echo "3. 권한 선택:"
echo "   - Workers Scripts:Edit"
echo "   - Workers KV Storage:Edit"
echo "   - Cloudflare Pages:Edit"
echo "4. 새 토큰을 GitHub Secrets에 등록"
echo ""

echo "⚡ 방법 2: 수동 배포 (즉시 가능)"
echo "API 토큰 없이도 배포됩니다!"
echo ""
echo "📱 프론트엔드:"
echo "  - https://dash.cloudflare.com/pages"
echo "  - Upload assets → dist 폴더 업로드"
echo "  - 프로젝트명: mosi-second-job"
echo ""
echo "🔧 백엔드:"
echo "  - https://dash.cloudflare.com/workers"
echo "  - Create Application"
echo "  - 코드 직접 붙여넣기"
echo "  - 환경변수에 API 키 설정"
echo ""

echo "💡 결론: 권한 문제이니 새 계정이나 수동 배포 추천!"
echo ""